auth_app/urls.py
from django.urls import path
from .views import LinkTokenView, AccessTokenView, AccountsView


app_name = "auth_app"

urlpatterns = [
    path('get_link_token/', LinkTokenView.as_view(), name='get_link_token'),
    path('get_access_token/', AccessTokenView.as_view(), name='get_access_token'),
    path('accounts/', AccountsView.as_view(), name='accounts'),
]

iDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('auth_app.urls', namespace="auth_app")),
    path('payment/', include('stripe_app.urls', namespace="stripe_app")),
]

stripe_app/urls.py
from django.urls import path
from .views import WebhookView, InsertLinkView, InvoiceView, ProofPaymentView, AuthorizePaymentView


app_name = "stripe_app"

urlpatterns = [
    path('webhook/', WebhookView.as_view(), name='webhook'),
    path('insert-link/', InsertLinkView.as_view(), name='insert_link'),
    path('invoice/<str:id>/', InvoiceView.as_view(), name='invoice'),
    path('proof-payment/', ProofPaymentView.as_view(), name='proof_payment'),
    path('payment/', AuthorizePaymentView.as_view(), name='payment'),
]

stripe_app/models.py
from django.db import models

# Create your models here.

stripe_app/views.py
import json
import stripe
from functools import wraps
from datetime import datetime
from django.http import HttpResponse
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from iDjango.settings import STRIPE_BEARER
from utils.common_functions import format_date, get_schema
from auth_app.views import AccountsMixin

stripe.api_key = STRIPE_BEARER


def get_info_from_request(decorated):
    @wraps(decorated)
    def wrapper(api, request, *args, **kwargs):
        access_token = request.session.get('access_token')
        invoice_id = request.session.get('invoice_id')
        account_id = request.session.get('account_id')
        if not all((access_token, invoice_id, account_id)):
            return render(request, 'stripe_app/error.html')
        return decorated(api, request, *args, **kwargs)
    return wrapper


@method_decorator(csrf_exempt, name='dispatch')
class WebhookView(View):
    """ stripe.error.InvalidRequestError: Invalid URL: URL must be publicly accessible. """

    def get(self, request):
        # TODO not localhost link
        try:
            stripe.WebhookEndpoint.create(
                url='http://localhost:8000/payment/insert-link/',
                enabled_events=[
                    'invoice.created',
                ],
            )
            return HttpResponse(status=200)
        except Exception as e:
            import traceback
            traceback.print_exc()
            return HttpResponse(status=400)


@method_decorator(csrf_exempt, name='dispatch')
class InsertLinkView(View):
    """ Insert link to invoice into field memo (description) """

    def post(self, request):
        raw_payload = request.body
        payload = json.loads(raw_payload)
        try:
            event = stripe.Event.construct_from(
                payload, stripe.api_key
            )
            invoice_id = payload.get("data", {}).get("object", {}).get("id")
        except ValueError as e:
            return HttpResponse(status=400)
        print(event.type)
        if event.type == 'invoice.created':
            schema = get_schema(request.is_secure())
            invoice_redirect_url = f'{schema}{request.get_host()}/user/invoice/{invoice_id}'
            invoice = stripe.Invoice.modify(
                invoice_id,
                description=f'Please follow link for ACH Direct Debit payment {invoice_redirect_url}',
            )
        return HttpResponse(status=200)


class InvoiceMixin:
    """  Class for handling invoice's views """
    _fields_to_represent_invoice = (
        'period_end', 'customer_name', 'status', 'number', 'subtotal', 'total', 'invoice_pdf', 'created', 'paid'
    )
    _fields_to_represent_line_invoice = (
        'quantity', 'description', 'unit_amount'
    )

    @staticmethod
    def get_invoice(invoice_id: str) -> dict:
        invoice_details = stripe.Invoice.retrieve(invoice_id)
        return invoice_details

    def search(self, line) -> dict:
        result = {}
        for item in line.items():
            if isinstance(item[1], dict):
                result.update(self.search(item[1]))
            elif item[0] in self._fields_to_represent_line_invoice:
                result.update({item[0]: item[1]})
        return result

    def create_context_from_invoice(self, invoice_id: str) -> dict:
        try:
            invoice_details = self.get_invoice(invoice_id)
            result = {
                invoice_key: invoice_details.get(invoice_key)
                for invoice_key in self._fields_to_represent_invoice
            }
            if result.get('created') > datetime.timestamp(datetime.now()):
                return {'error': 'invoice link is expired'}
            # result = dict(filter(lambda elem: elem[0] in self._fields_to_represent_invoice, invoice_details.items()))
            lines = invoice_details.get('lines', {}).get('data', [])
            result.update({'products': [self.search(line=line) for line in lines]})
            return result
        except Exception as e:
            import traceback
            traceback.print_exc()
            # TODO beautiful error
            return {'error': ''}


class InvoiceView(View, InvoiceMixin):
    """ Detail view of invoice (all info is getting from Stripe by API) """

    def get(self, request, *args, **kwargs):
        invoice_id = kwargs.get("id")
        request.session['invoice_id'] = invoice_id
        context = self.create_context_from_invoice(
            invoice_id=invoice_id
        )
        print(context)
        if 'error' in context:
            return render(request, 'stripe_app/error.html')
        return render(request, 'stripe_app/invoice_detail.html', context)


class ProofPaymentView(View, InvoiceMixin, AccountsMixin):
    """ Page with invoice and selected account views """

    @get_info_from_request
    def post(self, request):
        selected_account_id = request.POST.get('account')
        access_token = request.session.get('access_token')
        invoice_id = request.session.get('invoice_id')
        request.session['account_id'] = selected_account_id
        invoice = self.create_context_from_invoice(
            invoice_id=invoice_id
        )
        accounts = self.get_accounts(
            access_token=access_token,
            account_id=selected_account_id
        )
        if 'error' in invoice or 'error' in accounts:
            return render(request, 'stripe_app/error.html')
        context = {**invoice, **accounts}
        return render(request, 'stripe_app/proof_payment.html', context)


class AuthorizePaymentView(View, AccountsMixin):
    """ Payment! """

    @get_info_from_request
    def get(self, request):
        access_token = request.session.get('access_token')
        invoice_id = request.session.get('invoice_id')
        account_id = request.session.get('account_id')
        bank_account_token = self.create_bank_account_token(access_token=access_token, account_id=account_id)
        if 'error' in bank_account_token:
            return render(request, 'stripe_app/error.html')
        invoice_details = stripe.Invoice.retrieve(invoice_id)
        customer_id = invoice_details.get('customer')
        customer = stripe.Customer.modify(
            customer_id,
            source=bank_account_token.get('stripe_bank_account_token'),
        )
        payment = stripe.Invoice.pay(invoice_id, source=customer.get('default_source'))
        return render(request, 'stripe_app/result_payment.html')

stripe_app/templates/stripe_app/base.html
{% load static %}
{% load crispy_forms_tags %}

<!doctype html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!--    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}"/>-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <title>
      {% block title %}
      {% endblock %}
    </title>
  </head>

  <body>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

stripe_app/templates/stripe_app/error.html
{% extends "stripe_app/base.html" %}

{% block title %}
  Accounts
{% endblock title %}

{% block content %}

<p>Something was wrong</p>

{% endblock %}

stripe_app/templates/stripe_app/invoice_description.html
<p>Invoice from iTechArtGroup</p>
<p>Invoice {{ number }}</p>
(<a href="{{ invoice_pdf }}">Download as PDF</a>)

<p>Amount Due {{  total }}</p>
<p>Date Due {{  period_end }}</p>
<p>Billed To {{ customer_name }}</p>

<p>Summary</p>
{% for product in products %}
  <p>{{product.product_name}} x {{product.quantity}}</p>
  <p>{{product.unit_amount}}</p>
{% endfor %}

<p>Subtotal {{  subtotal }}</p>
<p>Amount Due {{  total }}</p>

stripe_app/templates/stripe_app/invoice_detail.html
{% extends "stripe_app/base.html" %}
{% load static %}
{% block title %}
  invoice
{% endblock title %}

{% block content %}

{% include "stripe_app/invoice_description.html" %}

{% if paid %}
  {{status}}
{% else %}
  <button id="linkButton">Start payment process</button>
{% endif %}

<script src="https://cdn.plaid.com/link/v2/stable/link-initialize.js"></script>
<!--<script src="{% static '/link-initialize.js' %}"></script>-->
<script type="text/javascript">
  let linkButton = document.getElementById('linkButton');

  (async function() {
    const fetchLinkToken = async () => {
      const response = await fetch("{% url 'auth_app:get_link_token' %}", { method: 'POST', headers: { 'X-CSRFToken': '{{ csrf_token }}' },});
      const responseJSON = await response.json();
      if (response.status === 200) return responseJSON.link_token;
      if (response.status === 400) {
          linkButton.disabled = true;
      }
    };

    let token = await fetchLinkToken();
    // let token = '{{ link_token }}';

    const configs = {
      token: token,
      receivedRedirectUri: null,
      onSuccess: async function(public_token, metadata) {
        const response = await fetch("{% url 'auth_app:get_access_token' %}", {
          method: 'POST',
          headers: { 'X-CSRFToken': '{{ csrf_token }}' },
          body: JSON.stringify({ public_token: public_token }),
        });
        const responseJSON = await response.json();
      },
      onExit: async function(err, metadata) {
        if (err != null && err.error_code === 'INVALID_LINK_TOKEN') {
          linkHandler.destroy();
          linkHandler = Plaid.create({
            ...configs,
            token: await fetchLinkToken(),
          });
        }
        if (err != null) {
          // Handle any other types of errors.
        }
      },
      onEvent: (eventName, metadata) => {
        // send event and metadata to self-hosted analytics
        if (eventName === 'HANDOFF') {
          window.location = "{% url 'auth_app:accounts' %}"
        }
      },
    };

    var linkHandler = Plaid.create(configs);

    // Trigger the authentication view
    linkButton.onclick = function() {
      linkHandler.open();
    };
  })();
</script>

{% endblock %}

stripe_app/templates/stripe_app/proof_payment.html
{% extends "stripe_app/base.html" %}

{% block title %}
  invoice
{% endblock title %}

{% block content %}
{% csrf_token %}

{% include "stripe_app/invoice_description.html" %}

<p>Account for payment</p>
<a href="{% url 'auth_app:accounts' %}">change</a>


{% for account in accounts %}
<div class="form-check">
  <label class="form-check-label">
    {{account.name}}
    ********{{account.mask}}
  </label>
</div>
{% endfor %}

<a href="{% url 'stripe_app:payment' %}">Authorize payment</a>

<!--<button id="linkButton">Authorize payment</button>-->

{% endblock %}

stripe_app/templates/stripe_app/result_payment.html
{% extends "stripe_app/base.html" %}

{% block title %}
  invoice
{% endblock title %}

{% block content %}

<p>YESSSSSSSSSSSSSSSSSSSSSSS</p>

{% endblock %}